# Those values are set by Maven filtering
# and will be replaced with a valid version number during the build process.
apiVersion: v2
name: @project.artifactId@
description: A Helm chart for Spring 6 Projects
type: application
version: @helm.chart.version@
appVersion: @project.version@

dependencies:
  - name: kbe-brewery-gateway-jms
    alias: jms
    version: @helm.chart.version@
    repository: file://charts/jms
    condition: jms.enabled
